# Generated by Django 5.0.3 on 2024-07-11 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='libraries',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='library_app.library'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='books',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='library_app.book'),
            preserve_default=False,
        ),
    ]
