# Generated by Django 5.0.3 on 2024-07-16 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0002_book_libraries_review_books'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='books',
            new_name='review',
        ),
        migrations.AlterField(
            model_name='book',
            name='editorial',
            field=models.CharField(max_length=120),
        ),
    ]
