# Generated by Django 5.0.3 on 2024-07-16 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0003_rename_books_review_review_alter_book_editorial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review',
            new_name='books',
        ),
    ]
